Add TN Logo
AlaskaAirlines/Icons pull request #127
Opened 2022-06-17 23:40 UTC by EvanFrostone

# Alaska Airlines Pull Request

Adds The TN tail logo.
**Fixes:** # (issue, if applicable)

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-06-17 23:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AlaskaAirlines/Icons?pullRequest=127) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AlaskaAirlines/Icons?pullRequest=127) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AlaskaAirlines/Icons?pullRequest=127) it.</sub>

2022-06-18 00:00 UTC, MattSidor requested changes
Please refer to the [Auro Design System Contributing Guidelines](http://auro.alaskaair.com/contributing) and create a feature branch that follows our feature branch naming syntax, as well as an amended commit message that follows the conventional commits pattern.

Once these changes are made, this should be ready for approval.

2022-06-18 00:12 UTC, MattSidor commented
Sorry, I just noticed one more change that needs to be made. the json file in `src/data/logoIcons` also needs to be updated with metadata on this new icon.

2022-06-18 00:40 UTC, closed without merging

2022-06-18 00:41 UTC, EvanFrostone commented
https://github.com/AlaskaAirlines/Icons/pull/128
Closing in favor of this second PR