Fix demo building for windows filesystems
AlaskaAirlines/Icons pull request #162
Opened 2022-11-28 18:37 UTC by mikearche

# Alaska Airlines Pull Request
This PR should resolve some issues that I was having running the demo project on a windows filesystem. There are also some minor improvements made to how we reference files.

I tested this on both windows and macos, and it works great on both ends now! 🎉

**Fixes:** #153 

## Summary:

This change updates a lot of our path references to use `path.join` so that our path references are not os specific.

Also found a bug with the `copyfiles` dependency requiring us to use double quotes on glob references for windows filesystems. See [this link](https://github.com/calvinmetcalf/copyfiles/issues/61) for more info.

## Type of change:

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-11-29 03:39 UTC, braven112 commented
@mikearche  You are my hero!!  Thanks for looking into this.

2022-11-30 21:21 UTC, blackfalcon requested changes
Last commit merged down from the remote and merges the last release with this new work. Please remove the merge commit and rebase off of main.

2022-12-01 17:26 UTC, mikearche commented
Removed the merge commit, and rebased! Should be good to go now.

2022-12-05 21:39 UTC, blackfalcon approved these changes

2022-12-05 21:39 UTC, merged