Update and add new Ravn logo
AlaskaAirlines/Icons pull request #181
Opened 2023-02-09 22:00 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #177 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

* Update to use new logo for RAVN Alaska
* Add RAVN Alaska logomark

## Type of change:

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-02-09 23:42 UTC, jason-capsule42 requested changes

2023-02-09 23:42 UTC, jason-capsule42 commented on src/data/logoIcons.json
> +      "name": "logo-RA",
RA is the wrong IATA - needs to stay as 7H.
```suggestion
      "name": "logo-7H",
```

2023-02-15 20:25 UTC, blackfalcon approved these changes

2023-02-15 20:38 UTC, merged

2023-02-15 20:42 UTC, AuroDesignSystem commented
:tada: This PR is included in version 4.21.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/icons/v/4.21.2)
- [GitHub release](https://github.com/AlaskaAirlines/Icons/releases/tag/v4.21.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: