Added destination icons
AlaskaAirlines/Icons pull request #257
Opened 2024-07-12 15:38 UTC by SLROS

# Alaska Airlines Pull Request

Added destination icons: flag-stroke, mountain-stroke and snowflake-stroke

**Resolves:** #256

## Summary:

Added missing destination icons for Google NLS work

## Type of change:

- [X] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [X] My update follows the CONTRIBUTING guidelines of this project
- [X] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-07-12 20:49 UTC, blackfalcon requested changes
Please update code commit to follow our Contributing Guidelines. 

https://github.com/AlaskaAirlines/WC-Generator/blob/master/.github/CONTRIBUTING.md#conventional-commits

2024-07-12 20:49 UTC, blackfalcon commented on src/icons/flag-stroke.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
```suggestion
<svg>
```

2024-07-12 20:49 UTC, blackfalcon commented on src/icons/flag-stroke.svg
> +<path d="M18.9969 11.1908L18.9948 11.178C18.9573 10.9552 18.8039 10.2256 18.6094 9.3021L18.6091 9.3008C18.2358 7.52708 17.7245 5.09818 17.5463 3.96218C17.5268 3.83904 17.5011 3.70782 17.4439 3.58012C
Remove all `fill` color references from SVG. Please see https://github.com/AlaskaAirlines/Icons/blob/master/README.md#do

Please address with all included icons.

2024-07-12 20:49 UTC, blackfalcon commented on src/icons/flag-stroke.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Please address with all included icons.

2024-07-15 15:28 UTC, SLROS commented on src/icons/flag-stroke.svg
> +<path d="M18.9969 11.1908L18.9948 11.178C18.9573 10.9552 18.8039 10.2256 18.6094 9.3021L18.6091 9.3008C18.2358 7.52708 17.7245 5.09818 17.5463 3.96218C17.5268 3.83904 17.5011 3.70782 17.4439 3.58012C
Fixed

2024-07-15 15:28 UTC, SLROS commented on src/icons/flag-stroke.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
@blackfalcon fixed

2024-07-15 16:17 UTC, blackfalcon approved these changes

2024-07-15 16:18 UTC, merged