Add new tail logos
AlaskaAirlines/Icons pull request #64
Opened 2021-02-03 05:32 UTC by blackfalcon

# Alaska Airlines Pull Request

**Fixes:** #61 

## Summary:

<img width="1526" alt="Screen Shot 2021-02-02 at 9 22 31 PM" src="https://user-images.githubusercontent.com/181089/106702820-dd2e4500-659d-11eb-9108-718703c8dd46.png">

## Type of change:

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [x] add new tail logos 

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-02-03 17:39 UTC, gusnaughton requested changes

2021-02-03 17:39 UTC, gusnaughton commented on src/data/logoIcons.json
> +      "desc": "Logo image for Aer Lingus Airlines",
Please remove 'Airlines

2021-02-03 17:39 UTC, gusnaughton commented on src/data/logoIcons.json
> +      "desc": "Logo image for Condor Airlines",
Please remove Airlines

2021-02-03 17:39 UTC, gusnaughton commented on src/data/logoIcons.json
> +      "desc": "Logo image for Emirates Airlines",
Please change to 'Airline'

2021-02-03 17:39 UTC, gusnaughton commented on src/data/logoIcons.json
> +      "title": "Iceland Airlines",
Please change to Icelandair

2021-02-03 17:39 UTC, gusnaughton commented on src/data/logoIcons.json
> +      "desc": "Logo image for Iceland Airlines",
Please change to Icelandair

2021-02-03 17:39 UTC, gusnaughton commented on src/data/logoIcons.json
> +      "title": "Latam Airlines",
LATAM

2021-02-03 17:39 UTC, gusnaughton commented on src/data/logoIcons.json
> +      "desc": "Logo image for Latam Airlines",
LATAM

2021-02-03 17:39 UTC, gusnaughton commented on src/data/logoIcons.json
> +      "title": "Latam Airlines",
LATAM

2021-02-03 17:39 UTC, gusnaughton commented on src/data/logoIcons.json
> +      "desc": "Logo image for Latam Airlines",
LATAM Airlines Peru

2021-02-03 17:39 UTC, gusnaughton commented on src/data/logoIcons.json
> +      "title": "EL AL Airlines",
El Al

2021-02-03 17:39 UTC, gusnaughton commented on src/data/logoIcons.json
> +      "desc": "Logo image for EL AL Airlines",
El Al Israel Airlines

2021-02-03 17:51 UTC, vidalmenAS approved these changes

2021-02-03 21:47 UTC, gusnaughton approved these changes

2021-02-04 18:25 UTC, merged

2021-02-04 18:27 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 4.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/icons/v/4.4.0)
- [GitHub release](https://github.com/AlaskaAirlines/Icons/releases/tag/v4.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: